name: build_site.yml
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  contents: write


jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
          clean: false
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Installing Joplin
        run: NPM_CONFIG_PREFIX=~/.joplin-bin npm install --loglevel=error -g joplin
      - name: configure joplin sync
        id: joplin_sync
        run: |
          j() { "$HOME/.joplin-bin/bin/joplin" "$@"; }
          j config sync.target 9
          j config sync.9.path "${{ secrets.JOPLIN_SERVER_URL }}"
          j config sync.9.username "${{ secrets.JOPLIN_USERNAME }}"
          j config sync.9.password "${{ secrets.JOPLIN_PASSWORD }}"
          j sync
          deploy=$(j cat ${{ secrets.JOPLIN_CONFIG_NOTE_ID }} | grep "deploy:" | awk '{print $2}')
          if [ "$deploy" = "true" ]; then
            j set ${{ secrets.JOPLIN_CONFIG_NOTE_ID }} body "deploy: false"
            j sync
            # copy the site to the ./sync directory
            j export --notebook joekaufeld.com --format md sync
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Hugo
        if: steps.joplin_sync.outputs.should_deploy == 'true'
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.155.3"
          extended: true

      - name: Install dependencies
        if: steps.joplin_sync.outputs.should_deploy == 'true'
        run: sudo apt install exiftool -y

      - name: Merge site content
        if: steps.joplin_sync.outputs.should_deploy == 'true'
        run: |
          rsync -avz sync/joekaufeld.com/ content

      - name: Build
        if: steps.joplin_sync.outputs.should_deploy == 'true'
        run: hugo --minify

      - name: Merge site resources
        if: steps.joplin_sync.outputs.should_deploy == 'true'
        run: rsync -avz sync/_resources public

      - name: Strip EXIF data
        if: steps.joplin_sync.outputs.should_deploy == 'true'
        run: exiftool -all= public/_resources/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: steps.joplin_sync.outputs.should_deploy == 'true' && github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_branch: gh-pages
          publish_dir: ./public

      - name: Notify
        if: steps.joplin_sync.outputs.should_deploy == 'true'
        run: curl -H prio:low -d "Website deployed!" ${{ secrets.NOTIFY_URL }}
